### ISSUE TITLE
Allow users to have custom configurations

### ISSUE THREAD

**Issue by refi64** [timniederhausen/gn-build#1]
My idea:

Add `import("//BUILDCONFIG.gn")` to the top of `config/BUILDCONFIG.gn`. That would allow users of these build scripts to define their own settings _before_ `config/BUILDCONFIG.gn` is executed.

**Comment by timniederhausen** [comment]
hmm, that's one way to do it.

My current workflow is to just fork the repo for the project I want to use it with and change the relevant files directly. Then I just need to add it as a submodule/DEPS-entry and I'm done. I guess that's the easiest approach, especially if you want to change a lot of details (e.g. ignored warnings, ...)

Besides: Wouldn't all the defaults in your `//BUILDCONFIG.gn` be overwritten by `config/BUILDCONFIG.gn`?

**Comment by timniederhausen** [comment]
btw.: you can also change the path of the buildconfig file in your root `.gn`:

Example:

```
buildconfig = "//build/config/BUILDCONFIG.gn"
```

**Comment by refi64** [comment]
Ah, right. I knew that but managed to forgot for just long enough to file this issue. Closing.
