### ISSUE TITLE
A little hard-code when '_ParseClVersion' executed.

### ISSUE THREAD

**Issue by joe2018Outlookcom** [timniederhausen/gn-build#11]
Here is the point:
[https://github.com/timniederhausen/gn-build/blob/494b5ee10ebae949d464bee0c83eb1f88b15eaa1/toolchain/win/toolchain.py#L145-L149](https://github.com/timniederhausen/gn-build/blob/494b5ee10ebae949d464bee0c83eb1f88b15eaa1/toolchain/win/toolchain.py#L145-L149)
`    m = re.search(r'Version ([0-9.]+)', line)`

However, in a Chinese version of cl.exe: 
![Annotation 2019-05-29 173817](https://user-images.githubusercontent.com/42833718/58546741-9587df80-8238-11e9-81e4-bd9016a2c000.png)
r'Version ([0-9.]+)' doesn't work.
A suggestion is to replace it with r' ([0-9.]+) ' .

**Comment by timniederhausen** [comment]
fixed in 6ebda2596e4b752760bac9d63449bcf136804aa5
