### ISSUE TITLE
Link error: unresolved external symbol ___atomic_compare_exchange_8, with Clang-cl in Win32.

### ISSUE THREAD

**Issue by joe2018Outlookcom** [timniederhausen/gn-build#19]
```text
1>[1/2] CXX obj/test/test_atomic/test_atomic/test_atomic.obj
1>[2/2] LINK test_atomic.exe test_atomic.exe.pdb
1>FAILED: test_atomic.exe test_atomic.exe.pdb
1>ninja -t msvc -e environment_x86 -- link.exe /nologo "-libpath:..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x86" "-libpath:..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86" "-libpath:..\..\..\..\..\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x86" "-libpath:..\..\..\..\..\Program Files (x86)\Windows Kits\10\lib\10.0.17763.0\um\x86" /OUT:./test_atomic.exe /PDB:./test_atomic.exe.pdb @./test_atomic.exe.rsp
1>test_atomic.obj : error LNK2019: unresolved external symbol ___atomic_compare_exchange_8 referenced in function _main
1>./test_atomic.exe : fatal error LNK1120: 1 unresolved externals
```

The problem happens in windows 10, using `Clang-cl` in `Win32`:

test\test_atomic\test_atomic.cpp
```C++
#include <atomic>
#include <cinttypes>

int main(void) {
  std::atomic<std::int64_t> temp;
  temp.load();
}
```

test\test_atomic\build.gn
```gn
executable("test_atomic") {
  sources = [
    "test_atomic.cpp",
  ]
}
```
gn && ninja command line
```cmd
gn gen out/llvm_win32_release --ide=vs2017 --winsdk=10.0.17763.0 --args="clang_base_path=\"C:/Program Files/LLVM\" is_clang=true target_cpu=\"x86\" is_debug=false"

ninja -C out/llvm_win32_release test_atomic

```

PS: The problem just happens in `LLVM+Win32`. There are no problem with `LLVM+Win64`, `Win32` and `Win64`.

**Comment by joe2018Outlookcom** [comment]
Sorry for reopen it, I need to merge it into mine master branch. Then Github.com close this issue automatically.

**Comment by timniederhausen** [comment]
It appears LLVM doesn't implement the atomic intrinsics for non-SSE x86 themselves but instead relies on libatomic.
However, in my local tests your code works fine even with `/arch:IA32`.

What LLVM version do you use?

**Comment by joe2018Outlookcom** [comment]
> It appears LLVM doesn't implement the atomic intrinsics for non-SSE x86 themselves but instead relies on libatomic.
> However, in my local tests your code works fine even with `/arch:IA32`.
> 
> What LLVM version do you use?

LLVM 11.0

Use choco to install it.

- choco install llvm --y
- Here is [the download link](https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/LLVM-11.0.0-win64.exe) of LLVM-11.0 .

PS: Try 10.0, the same as 11.0.

PS: The problem just happen with `std::atomic<std::int64_t>` 's `load()` operation. Try `std::atomic<std::int32_t>` would be okay. Also, try `std::atomic<std::int64_t>` 's `store()` operation would be okay.

**Comment by joe2018Outlookcom** [comment]
It seems that LLVM generate an extra symbol.

(Use LLVM 11.0, MSVC, Win32, `/arch:IA32`, `std::atomic<std::int64_t>`, `load()`)

It's [here](https://github.com/timniederhausen/gn-build/pull/20#issuecomment-722779520).

**Comment by timniederhausen** [comment]
Thanks for reporting, it appears LLVM versions below 9.0 used `lock cmpxchg8b` with `/arch:IA32` but later versions seem to think that `/arch:IA32` means i486 (or maybe i386).

Since we no longer support any Visual Studio version that defaults to `/arch:IA32` I don't see why we would need to keep that flag.
