### ISSUE TITLE
Should I use this for a new project?

### ISSUE THREAD

**Issue by raizam** [timniederhausen/gn-build#3]
First of all thank you for this great work, this repo was the only way to get GN working for me.
Is this going to be maintained?

**Comment by timniederhausen** [comment]
Hi,

I currently use GN (with this //build directory) for a number of projects, so it's certainly going to be maintained.

Regarding the lack of recent commits:
Right now gn-build has all the features I require (and is working fine), so there simply wasn't any need for changes in the last months.
Perhaps I'll add support for more platforms in the future (notably Android), but that's still uncertain.

If there's anything you find missing, please open an issue and I'll look into it when I have time.

**Comment by raizam** [comment]
Thanks again for this, I think this is the solution I'm about to adopt :)
There still quite a learning curve, but I believe it's worthed it :+1:
