### ISSUE TITLE
Include errors

### ISSUE THREAD

**Issue by garciaadrian** [timniederhausen/gn-build#6]
Trying to include a header from another target fails. I don't know what I'm doing wrong since the following testcase works with a different build config

I created a [testcase](https://github.com/garciaadrian/gn-testcase) that will fail with latest commit

**Comment by timniederhausen** [comment]
This works with Chromium's //build because they add the project root to the global `include_dirs` defaults.

As this is quite specific to Chromium's project layout it's not included here.

**Comment by timniederhausen** [comment]
If you want this behavior back, add the following to `config/BUILD.gn`:
```gn
config("default_include_dirs") {
  include_dirs = [
    "//",
  ]
}
```
and reference it in your target's `public_configs` or the global `default_compiler_configs` (found in `BUILDCONFIG.gn`)

**Comment by garciaadrian** [comment]
Thanks! I'm starting to understand how this works
