### ISSUE TITLE
problem with .obj out directory

### ISSUE THREAD

**Issue by raizam** [timniederhausen/gn-build#9]
Hi,

Thanks a lot for maintaining this.

I'm currently having issues with a project that has source files with the same name across different folders. This results with different .obj files with the same name in the same directory, without keeping the original folder hierarchy.
Would it be possible to output these while reproducing the original folder structure?

**Comment by timniederhausen** [comment]
Yes, that's possible.

In [toolchain/win/BUILD.gn](https://github.com/timniederhausen/gn-build/blob/master/toolchain/win/BUILD.gn) you simply have to change `object_subdir` to this:
```gn
    object_subdir = "{{target_out_dir}}/{{label_name}}/{{source_root_relative_dir}}"
```

I'm currently not sure why this isn't done by default. Maybe some paths would exceed the old 256 character limit on Windows. This would be more of an issue for Chromium than for this standalone version.

I'll think about changing it in this repo. Until then you can just add it to your fork or split your target into multiple `source_set`s. 

Thanks for bringing this up!

**Comment by raizam** [comment]
I came up with the same solution but a little less elegant than yours 
https://github.com/raizam/gn-build/tree/fix-obj-collisions
was almost about to submit PR, but now I'll just wait for you to think about it =)

Thanks!
